### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'orientation') when deploy on deno

### ISSUE THREAD

**Issue by Thai2706** [vidstack/player#1196]
### Current Behavior:

I tried to use Vidstack player  in my Nuxt.js project, it's work well on local machine but when I deploy to [deno](https://deno.com/deploy), I got this: 
```
The deployment failed: UNCAUGHT_EXCEPTION

TypeError: Cannot read properties of undefined (reading 'orientation')
    at canRotateScreen (file:///src/server/index.ts:135354:37)
    at canOrientScreen (file:///src/server/index.ts:135351:10)
    at file:///src/server/index.ts:135832:20
```
and when I deploy to [Vercel](https://vercel.com/), it stuck at home page.

### Steps To Reproduce:

1. I followed installation step at: [Vidstack](https://www.vidstack.io/docs/player/getting-started/installation/vue?bundler=nuxt&provider=video&styling=default-layout)
2. Import player & CSS (I tried `import 'vidstack/bundle';` but it doesn't work):
```javascript
import 'vidstack/player';
import 'vidstack/player/layouts/default';
import 'vidstack/player/ui';
import 'vidstack/player/styles/default/theme.css';
import 'vidstack/player/styles/default/layouts/video.css';
```
3. Add player
```html
<media-player title="Sprite Fight" src="https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/low.mp4">
  <media-provider></media-provider>
  <media-video-layout thumbnails="https://image.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/storyboard.vtt"></media-video-layout>
</media-player>
```

### Environment:

- Framework: Vue.js
- Meta Framework: Nuxt.js
- Node: 20.11.1
- OS: Windows 10 64-bit
- Browser: Chrome@122.0.6261.95

**Comment by mihar-22** [comment]
Deno wasn't included in our package exports so it was picking up the client bundle.

**Comment by mihar-22** [comment]
> I tried import 'vidstack/bundle'; but it doesn't work

This is very likely due to the `include` filter not matching your player component file path. You can either remove it or move the file to the correct path (default is in a `player/` directory).

```ts
import { vite as vidstack } from 'vidstack/plugins';

export default defineNuxtConfig({
  vite: {
    plugins: [
      // Include filter to only check specific files for components and styles.
      vidstack({ include: /player\// }),
    ],
  },
});
```
